_media_list:
    path:  /media/list/{context}
    defaults: { _controller: MajesMediaBundle:Admin:list, context: full }

_media_edit:
    path:  /media/edit/{context}/{id}
    defaults: { _controller: MajesMediaBundle:Admin:edit, context: full, id: null }

_media_edit_multiple:
    path:  /media/multiple/edit/{context}
    defaults: { _controller: MajesMediaBundle:Admin:multipleEdit, context: full }

_media_delete:
    path:  /media/delete/{context}/{id}
    defaults: { _controller: MajesMediaBundle:Admin:delete, context: full, id: null }

_media_picker:
    path:  /media/picker/{context}/{id}
    defaults: { _controller: MajesMediaBundle:Admin:mediapicker, context: full, id: null }
