_media_load:
    path:  /media/load/{id}/{crop}/{width}/{height}
    defaults: { _controller: MajesMediaBundle:Media:load, crop: 0, width: null, height: null}


_media_download:
    path:  /media/download/{id}
    defaults: { _controller: MajesMediaBundle:Media:download}
