parameters:
    media:
        sizes:
            xxlarge: 
                width: 3000
                ratio: 2
            xlarge:
                width: 1400
                ratio: 1
            large: 
                width: 1148
                ratio: 1
            medium:
                width: 988
                ratio: 1
            small:
                width: 748
                ratio: 1
            xsmall:
                width: 480
                ratio: 1

services:
    majesmedia.twig.media_extension:
        class: Majes\MediaBundle\Twig\MediaExtension
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }

    majesmedia.image_type_extension:
        class: Majes\MediaBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, alias: file }

    majesmedia.form.type.media:
        class: Majes\MediaBundle\Form\MediaType
        tags:
            - { name: form.type, alias: media }
            
    majesmedia.mediaService:
        class: Majes\MediaBundle\Services\MediaService
        arguments: [@doctrine.orm.entity_manager, '%media%']
